# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Afosto < Formula
  desc "CLI tool for interaction with Afosto/IO"
  homepage "https://afosto.com/"
  version "0.0.7"
  license "Apache-2.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/afosto/cli/releases/download/v0.0.7/cli_0.0.7_Darwin_x86_64.tar.gz"
    sha256 "e0fefb51b6bff2e895a17a206fef7f8f8e1592c6eb3e311e0e7bf6e9fd910b1c"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/afosto/cli/releases/download/v0.0.7/cli_0.0.7_Linux_x86_64.tar.gz"
    sha256 "70376482b8d55c98746361ae363501e722e801ff290e1f0479005a1ed9c514a1"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/afosto/cli/releases/download/v0.0.7/cli_0.0.7_Linux_arm64.tar.gz"
    sha256 "a8457da3f9611de75d28dab108e093ee2ca9bd7564793e99c2a130903157626f"
  end

  def install
    bin.install "afosto"
  end

  def caveats; <<~EOS
    Thanks for installing the Afosto CLI! If you have any feedback, please open up an issue at github.com/afosto/cli. Run `afosto login` to authenticate with the API.
  EOS
  end

  test do
    afosto version
  end
end
