# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AfostoCli < Formula
  desc "CLI tool for interaction with Afosto/IO"
  homepage "https://afosto.com/"
  version "0.0.5"
  license "Apache-2.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/afosto/cli/releases/download/v0.0.5/cli_0.0.5_Darwin_x86_64.tar.gz"
    sha256 "5f8c7cc52a8fdfd46a0b0c25f8a00bd5f4c7b5edacee8d095fadaf61509dd6d9"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/afosto/cli/releases/download/v0.0.5/cli_0.0.5_Linux_x86_64.tar.gz"
    sha256 "8aabad9daef65edbeb5dbedd914336215dcc262c06e234ba70b733167c025a35"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/afosto/cli/releases/download/v0.0.5/cli_0.0.5_Linux_arm64.tar.gz"
    sha256 "b06d642dd7470af2faab09d43d4bf1ffda2b363824ca0f6b23aa0095833696ba"
  end

  def install
    bin.install "cli"
  end
end
