# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AfostoCli < Formula
  desc "CLI tool for interaction with Afosto/IO"
  homepage "https://afosto.com/"
  version "0.0.9"
  license "Apache-2.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/afosto/cli/releases/download/v0.0.9/cli_0.0.9_Darwin_x86_64.tar.gz"
    sha256 "abc8b5f9a030a7a7a82ba9e63492c5dcdd548847886c3ff41153fdc72318211c"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/afosto/cli/releases/download/v0.0.9/cli_0.0.9_Linux_x86_64.tar.gz"
    sha256 "0e164e1c88c722e846fcc45449de410142cea6ca7ee36b7df0a83889f9aa80be"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/afosto/cli/releases/download/v0.0.9/cli_0.0.9_Linux_arm64.tar.gz"
    sha256 "d936b4fb645ce82fc9ab0a5a80c29d76ad45ff92e5c376757e7eb1dee6089a1c"
  end

  def install
    bin.install "afosto"
  end

  def caveats; <<~EOS
    Thanks for installing the Afosto CLI! If you have any feedback, please open up an issue at github.com/afosto/cli. Run `afosto login` to authenticate with the API.
  EOS
  end

  test do
    afosto version
  end
end
